import Head from "next/head"
import { useRef } from "react"
import { motion, useScroll } from "framer-motion"
import Image from "next/image"
import profileImg from "../../public/images/profile/developer-pic-2.jpg"
import Layout from "@/components/Layaout"
import TransitionEffect from "@/components/TransitionEffect"
import FramerSkills from "@/components/framer-skills/FramerSkills"
import ProgressMotionAbout from "@/components/ProgressMotionAbout"


import about1 from "../../public/images/aboutimg/ap1.webp"
import about2 from "../../public/images/aboutimg/ap2.webp"

import excel from "../../public/images/logo/excel.png"
import ilustrator from "../../public/images/logo/ilustrator.png"
import photoshop from "../../public/images/logo/photoshop.png"
import powerpoint from "../../public/images/logo/powerpoint.png"
import word from "../../public/images/logo/word.png"

import css from "../../public/images/logo/css.png"
import html from "../../public/images/logo/html.png"
import nodejs from "../../public/images/logo/nodejs.png"
import express from "../../public/images/logo/express.png"


const animateH1 = {
  initial: {
    opacity: 0
  },
  animate: {
    opacity: 1,
    transition: {
      delay: 0.9
    }
  }
}

function About() {
  return (
    <>
      <Head>
        <title>Bryan Josseph | Sobre mi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect></TransitionEffect>
      <main className="flex  w-full flex-col items-center justify-center dark:text-light">
        <Layout className="pt-16">
          <div className='w-full mx-auto py-2 flex items-center justify-center text-center mt-16 mb-28 h-[26rem] sm:mb-96 m-0'>
            <motion.h1 className='inline-block w-full text-black font-bold capitalize text-8xl sm:text-6xl' variants={animateH1} initial="initial" animate="animate">Hola de nuevo!<span className="text-yellow-400"> :)</span></motion.h1>
          </div>
          {/*content*/}
          <div className="w-full bg-[#fcfff8]/50">
            <div className=" flex px-40 py-10 sm:flex-col sm:px-0 sm:gap-5 gap-5">
              <div className="w-1/2 flex justify-center items-center sm:w-full">
                <p className="text-6xl sm:text-4xl sm:text-center">Mi nombre es <span className="font-bold text-yellow-400">Bryan Josseph YF</span></p>
              </div>
              <div className="w-1/2 flex justify-center sm:w-full">
                <Image src={profileImg} className="w-80 rounded-full" alt="foto de perfil"></Image>
              </div>
            </div>
            <p className="text-center font-medium">Soy estudiante de la carrera de marketing 😁</p>
          </div>
          {/**2 */}

          <div className="flex mt-10 gap-10 sm:flex-col">

            <div className="w-1/2 p-5 sm:w-full sm:p-0">
              <p className="text-6xl sm:text-5xl">Conoce mas sobre <span className="font-semibold text-yellow-400">mi</span></p>
              <p className="text-base p-5 sm:text-base sm:text-justify">Actualmente, soy estudiante de la carrera de Gestión y Marketing. Durante mi formación, he aprendido muchas cosas relacionadas con el mundo de los negocios y el marketing. Los temas que más me atraen son la investigación de mercado y el branding. Gracias a esta carrera, he podido desarrollar mucho mi lado creativo, estratégico, analítico y lógico. Como hobby, me gusta ver series, especialmente los dibujos animados, y programar.
                Sigo trabajando actualmente para seguir creciendo tanto personal como profesionalmente.
              </p>

              <div className="flex mt-5 p-5 sm:p-0 ">

                <Image src={about1} className="w-1/2" alt="habilidades"></Image>
                <Image src={about2} className="w-1/2" alt="habilidades"></Image>

              </div>
            </div>

            <div className="w-1/2 sm:w-full sm:p-0">
              <div className="sm:mb-10">
                <ProgressMotionAbout title="Software" svg={<svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                  <path fill-rule="evenodd" d="M3 4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h18a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H3Zm4.293 5.707a1 1 0 0 1 1.414-1.414l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L9.586 12 7.293 9.707ZM13 14a1 1 0 1 0 0 2h3a1 1 0 1 0 0-2h-3Z" clip-rule="evenodd" />
                </svg>
                }></ProgressMotionAbout>
                <div className="flex justify-center gap-5 mt-5">
                  <Image src={excel} className="size-10 sm:size-8" alt="software Office"/>
                  <Image src={ilustrator} className="size-10 sm:size-8" alt="software Office"/>
                  <Image src={photoshop} className="size-10 sm:size-8" alt="software Office"/>
                  <Image src={powerpoint} className="size-10 sm:size-8" alt="software Office"/>
                  <Image src={word} className="size-10" alt="software Office"/>
                </div>
                <div className="my-5">
                  <p className="font-thin ml-14">Otros:</p>

                  <div className="flex justify-center gap-5 mt-5">
                    <Image src={html} className="size-10 " alt="softwares"/>
                    <Image src={css} className="size-10" alt="softwares"/>
                    <Image src={nodejs} className="size-10" alt="softwares"/>
                    <Image src={express} className="size-10" alt="softwares"/>
                  </div>
                </div>
              </div>

              <div className="sm:mb-10">
                <ProgressMotionAbout title="Idioma" svg={<svg class="w-6 h-6 text-gray-800 " aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M4.37 7.657c2.063.528 2.396 2.806 3.202 3.87 1.07 1.413 2.075 1.228 3.192 2.644 1.805 2.289 1.312 5.705 1.312 6.705M20 15h-1a4 4 0 0 0-4 4v1M8.587 3.992c0 .822.112 1.886 1.515 2.58 1.402.693 2.918.351 2.918 2.334 0 .276 0 2.008 1.972 2.008 2.026.031 2.026-1.678 2.026-2.008 0-.65.527-.9 1.177-.9H20M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                </svg>
                } />
                <p className="font-medium text-center my-10"> Ingles - Escritura y conversación básica</p>
              </div>

              <div className="sm:my-20">
                <ProgressMotionAbout title="Cursos" svg={<svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                  <path fill-rule="evenodd" d="M6 2a2 2 0 0 0-2 2v15a3 3 0 0 0 3 3h12a1 1 0 1 0 0-2h-2v-2h2a1 1 0 0 0 1-1V4a2 2 0 0 0-2-2h-8v16h5v2H7a1 1 0 1 1 0-2h1V2H6Z" clip-rule="evenodd" />
                </svg>
                } />
                <div className="my-10 p-6 sm:my-5 sm:p-0">
                  <FramerSkills></FramerSkills>
                </div>
              </div>

            </div>
          </div>

        </Layout>

      </main>

    </>

  )

}

export default About



